### ISSUE TITLE
博主，请问post编辑正文的时候，是如何做到版面样式的添加的？

### ISSUE THREAD

**Issue by dbdoer** [flyhigher139/mayblog#1]
我在本地跑起来了，但是发现编辑内容的时候没有像wordpress那样的插件啊？

**Comment by flyhigher139** [comment]
@dbdoer 版面样式添加是指添加page么？  编辑内容是用markdown的，非所见即所得的页面

另外，你可以看看[OctBlog](https://github.com/flyhigher139/OctBlog)，它的编辑页面是用js优化过的

**Comment by dbdoer** [comment]
好的，谢谢。
