### ISSUE TITLE
没有用django的admin?

### ISSUE THREAD

**Issue by litp** [flyhigher139/mayblog#2]
我对这个项目很感兴趣，整个项目目录清楚明了，写的代码也都注释详细，是一个很好的可供学习的项目。我大概看了一下整个程序，你似乎没有用django自带的admin，整个admin的url都被指向到程序里的class based view页面，不知是否正确？另一个想请教的是这个blog的post中是否不能直接加入图片，只能加入指向外链图片的url？

**Comment by flyhigher139** [comment]
@litianpeng200 django自带的admin也可以打开，我在blog/readme里写了：

> Django's default admin: http://127.0.0.1:8000/admin2/

关于图片的问题，外链图片对博客系统来说，是最好的方案，在博客系统的服务器上托管静态文件的开销远大于博客本身。

未来可以在博客系统中加入静态文件管理功能，这个功能优先级比较低

**Comment by litp** [comment]
好，谢谢
